# Generated by Django 6.0.1 on 2026-01-27 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('from_date', models.CharField(max_length=10)),
                ('to_date', models.CharField(max_length=10)),
                ('days', models.FloatField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'leaves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(default='Activity', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'post_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
            ],
            options={
                'db_table': 'post_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attendance_records', serialize=False, to='api.employee')),
                ('date', models.CharField(max_length=10)),
                ('check_in', models.CharField(blank=True, max_length=20, null=True)),
                ('check_out', models.CharField(blank=True, max_length=20, null=True)),
                ('break_minutes', models.IntegerField(default=0)),
                ('worked_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attendance_logs', serialize=False, to='api.employee')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'attendance_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='likes', serialize=False, to='api.post')),
            ],
            options={
                'db_table': 'post_likes',
                'managed': False,
            },
        ),
    ]
