# Generated by Django 6.0.1 on 2026-01-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpstore',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP Store', 'verbose_name_plural': 'OTP Store entries'},
        ),
        migrations.AddField(
            model_name='otpstore',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otpstore',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpstore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otpstore',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
