# Generated by Django 6.0.1 on 2026-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_otpstore_options_otpstore_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTPStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email OTP Store',
                'verbose_name_plural': 'Email OTP Store entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
