# Generated by Django 6.0.1 on 2026-02-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailotpstore_alter_otpstore_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpstore',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
