# Generated by Django 6.0.1 on 2026-02-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_leaves_employee_alter_posts_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
