# Generated by Django 6.0.1 on 2026-01-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employees_leaves_postcomments_postimages_posts_teams_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComments',
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='attendance',
        ),
        migrations.DeleteModel(
            name='PostLikes',
        ),
    ]
