# Generated by Django 6.0.1 on 2026-01-29 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employees_remove_employee_team_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='core_attendance',
        ),
        migrations.AlterModelTable(
            name='attendancelogs',
            table='core_attendancelog',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='core_employee',
        ),
        migrations.AlterModelTable(
            name='leaves',
            table='core_leaverequest',
        ),
        migrations.AlterModelTable(
            name='posts',
            table='core_post',
        ),
        migrations.AlterModelTable(
            name='teams',
            table='core_team',
        ),
    ]
