# Generated by Django 6.0.1 on 2026-02-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_leaves_created_at_alter_posts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='notify_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
