# Generated by Django 6.0.1 on 2026-02-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leaves_notify_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='notify_to',
        ),
        migrations.AddField(
            model_name='leaves',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
