# Generated by Django 6.0.1 on 2026-02-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_leaves_notify_to_leaves_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='session',
            new_name='from_session',
        ),
        migrations.AddField(
            model_name='leaves',
            name='to_session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
