# Generated by Django 6.0.1 on 2026-02-04 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_session_leaves_from_session_leaves_to_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regularization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_checkout', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.employees', to_field='employee_id')),
            ],
            options={
                'db_table': 'core_regularization',
                'managed': True,
            },
        ),
    ]
