# Generated by Django 6.0.1 on 2026-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_regularization'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='shift_end',
            field=models.CharField(default='06:30 PM', max_length=20),
        ),
        migrations.AddField(
            model_name='teams',
            name='shift_start',
            field=models.CharField(default='09:30 AM', max_length=20),
        ),
    ]
