# Generated by Django 6.0.1 on 2026-02-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teams_shift_end_teams_shift_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('is_optional', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_holidays',
                'managed': True,
            },
        ),
    ]
