# Generated by Django 6.0.1 on 2026-02-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
