# Generated by Django 6.0.1 on 2026-02-05 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employees_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('days_per_year', models.FloatField()),
                ('carry_forward', models.BooleanField(default=False)),
                ('encashment', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_leavetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('allocated_days', models.FloatField(default=0)),
                ('consumed_days', models.FloatField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employees')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leavetype')),
            ],
            options={
                'db_table': 'core_employeeleavebalance',
                'managed': True,
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
