# Generated by Django 6.0.1 on 2026-02-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_leavetype_employeeleavebalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='team',
        ),
        migrations.AddField(
            model_name='employees',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.teams'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_teams', to='core.employees', to_field='employee_id'),
        ),
    ]
