# Generated by Django 6.0.1 on 2026-02-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_employees_team_employees_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='whatsapp_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
