# Generated by Django 6.0.1 on 2026-02-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teams_whatsapp_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='whatsapp_group_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
