# Generated by Django 4.2.16 on 2026-02-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_wfhrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFromHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(max_length=10)),
                ('to_date', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.employees', to_field='employee_id')),
            ],
            options={
                'db_table': 'core_wfh',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='WFHRequest',
        ),
    ]
