# Generated by Django 4.2.16 on 2026-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_workfromhome_delete_wfhrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelogs',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
