# Generated by Django 4.2.16 on 2026-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_attendancelogs_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='is_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
