# Generated by Django 4.2.16 on 2026-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_leaves_is_overridden'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
