# Generated by Django 4.2.16 on 2026-02-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_employees_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveOverrideRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('check_in', models.CharField(blank=True, max_length=20, null=True)),
                ('check_out', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.employees', to_field='employee_id')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='core.leaves')),
            ],
            options={
                'db_table': 'core_leaveoverriderequest',
                'managed': True,
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
