# Generated by Django 4.2.16 on 2026-02-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_leaveoverriderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveoverriderequest',
            name='location_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveoverriderequest',
            name='location_out',
            field=models.TextField(blank=True, null=True),
        ),
    ]
